name = "docs-engine-example"
type = "webpack"
account_id = "465876a47384341612732d0e6a113a08"
workers_dev = true

[site]
bucket = ".docs/public/" # Add pathPrefix here if necessary
entry-point = ".docs/workers-site"
